project_id = "xtfubistkgodiksegtcx"

[functions]
  [functions.analyze-job]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.esco-lookup]
    verify_jwt = false
  [functions.generate-pathways]
    verify_jwt = false
  [functions.scrape-company]
    verify_jwt = false
